/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Factory
-/
module

prelude
public import Init.Data.List.Basic
public import Init.Data.String.Basic

namespace RuntimeExterns

/-- Auto-generated from `tools/gen-emitzig-runtime-externs.py`. Do not edit by hand. -/
public def runtimeExternDeclsGenerated : List String := [
  "extern fn acos(_0: f64) callconv(.c) f64;",
  "extern fn acosf(_0: f32) callconv(.c) f32;",
  "extern fn acosh(_0: f64) callconv(.c) f64;",
  "extern fn acoshf(_0: f32) callconv(.c) f32;",
  "extern fn asin(_0: f64) callconv(.c) f64;",
  "extern fn asinf(_0: f32) callconv(.c) f32;",
  "extern fn asinh(_0: f64) callconv(.c) f64;",
  "extern fn asinhf(_0: f32) callconv(.c) f32;",
  "extern fn atan(_0: f64) callconv(.c) f64;",
  "extern fn atan2(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn atan2f(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn atanf(_0: f32) callconv(.c) f32;",
  "extern fn atanh(_0: f64) callconv(.c) f64;",
  "extern fn atanhf(_0: f32) callconv(.c) f32;",
  "extern fn cbrt(_0: f64) callconv(.c) f64;",
  "extern fn cbrtf(_0: f32) callconv(.c) f32;",
  "extern fn ceil(_0: f64) callconv(.c) f64;",
  "extern fn ceilf(_0: f32) callconv(.c) f32;",
  "extern fn cos(_0: f64) callconv(.c) f64;",
  "extern fn cosf(_0: f32) callconv(.c) f32;",
  "extern fn cosh(_0: f64) callconv(.c) f64;",
  "extern fn coshf(_0: f32) callconv(.c) f32;",
  "extern fn exit(_0: c_int) callconv(.c) noreturn;",
  "extern fn exp(_0: f64) callconv(.c) f64;",
  "extern fn exp2(_0: f64) callconv(.c) f64;",
  "extern fn exp2f(_0: f32) callconv(.c) f32;",
  "extern fn expf(_0: f32) callconv(.c) f32;",
  "extern fn fabs(_0: f64) callconv(.c) f64;",
  "extern fn fabsf(_0: f32) callconv(.c) f32;",
  "extern fn floor(_0: f64) callconv(.c) f64;",
  "extern fn floorf(_0: f32) callconv(.c) f32;",
  "extern fn lean_add_decl(_0: LeanObj, _1: usize, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_add_decl_bridge(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_add_decl_without_checking(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_align(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_alloc_ctor_memory(_0: c_uint) callconv(.c) LeanObj;",
  "extern fn lean_alloc_external(_0: ?*anyopaque, _1: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_alloc_mpz() callconv(.c) LeanObj;",
  "extern fn lean_alloc_object(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_alloc_sarray_would_overflow(_0: c_uint, _1: usize) callconv(.c) bool;",
  "extern fn lean_alloc_small(_0: c_uint, _1: c_uint) callconv(.c) ?*anyopaque;",
  "extern fn lean_alloc_small_object(_0: c_uint) callconv(.c) LeanObj;",
  "extern fn lean_alloc_string(_0: usize, _1: usize, _2: usize) callconv(.c) LeanObj;",
  "extern fn lean_apply_1(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_10(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_11(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_12(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj, _12: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_13(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj, _12: LeanObj, _13: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_14(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj, _12: LeanObj, _13: LeanObj, _14: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_15(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj, _12: LeanObj, _13: LeanObj, _14: LeanObj, _15: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_16(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj, _10: LeanObj, _11: LeanObj, _12: LeanObj, _13: LeanObj, _14: LeanObj, _15: LeanObj, _16: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_2(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_3(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_4(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_5(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_6(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_7(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_8(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_9(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: LeanObj, _6: LeanObj, _7: LeanObj, _8: LeanObj, _9: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_m(_0: LeanObj, _1: c_uint, _2: [*c]LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_apply_n(_0: LeanObj, _1: c_uint, _2: [*c]LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_array_capacity(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_array_data_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_array_fget(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_fget_borrowed(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_fset(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_fswap(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_get(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_get_panic(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_mk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_pop(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_push(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_set(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_set_core(_0: LeanObj, _1: usize, _2: LeanObj) callconv(.c) void;",
  "extern fn lean_array_set_panic(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_set_size(_0: LeanObj, _1: usize) callconv(.c) void;",
  "extern fn lean_array_swap(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_sz(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_to_list(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_uset(_0: LeanObj, _1: usize, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_array_uswap(_0: LeanObj, _1: usize, _2: usize) callconv(.c) LeanObj;",
  "extern fn lean_big_int64_to_int(_0: i64) callconv(.c) LeanObj;",
  "extern fn lean_big_int_to_int(_0: c_int) callconv(.c) LeanObj;",
  "extern fn lean_big_int_to_nat(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_big_size_t_to_int(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_big_usize_to_nat(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_bool_to_int16(_0: u8) callconv(.c) u16;",
  "extern fn lean_bool_to_int32(_0: u8) callconv(.c) u32;",
  "extern fn lean_bool_to_int64(_0: u8) callconv(.c) u64;",
  "extern fn lean_bool_to_int8(_0: u8) callconv(.c) u8;",
  "extern fn lean_bool_to_isize(_0: u8) callconv(.c) usize;",
  "extern fn lean_bool_to_uint16(_0: u8) callconv(.c) u16;",
  "extern fn lean_bool_to_uint32(_0: u8) callconv(.c) u32;",
  "extern fn lean_bool_to_uint64(_0: u8) callconv(.c) u64;",
  "extern fn lean_bool_to_uint8(_0: u8) callconv(.c) u8;",
  "extern fn lean_bool_to_usize(_0: u8) callconv(.c) usize;",
  "extern fn lean_box_uint16_zig_impl(_0: u16) callconv(.c) LeanObj;",
  "extern fn lean_box_uint8_zig_impl(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_copy_slice(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: u8) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_data(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_fset(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_get(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_byte_array_hash(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_byte_array_mk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_push(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_set(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_byte_array_uget(_0: LeanObj, _1: usize) callconv(.c) u8;",
  "extern fn lean_byte_array_uset(_0: LeanObj, _1: usize, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_byteslice_beq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_char_default_value() callconv(.c) u32;",
  "extern fn lean_check_heartbeat() callconv(.c) void;",
  "extern fn lean_check_interrupted() callconv(.c) void;",
  "extern fn lean_check_memory(_0: [*:0]const u8) callconv(.c) void;",
  "extern fn lean_check_stack(_0: [*:0]const u8) callconv(.c) void;",
  "extern fn lean_check_system(_0: [*:0]const u8, _1: bool) callconv(.c) void;",
  "extern fn lean_checked_assign(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_chmod(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_closure_arg_cptr(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_closure_arity(_0: LeanObj) callconv(.c) c_uint;",
  "extern fn lean_closure_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_closure_data_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_closure_fun(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_closure_get(_0: LeanObj, _1: c_uint) callconv(.c) LeanObj;",
  "extern fn lean_closure_max_args(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_closure_num_fixed(_0: LeanObj) callconv(.c) c_uint;",
  "extern fn lean_compacted_region_free(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_compacted_region_read(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_compacted_region_save(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: u8) callconv(.c) LeanObj;",
  "extern fn lean_copy_byte_array(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_copy_expand_array(_0: LeanObj, _1: bool) callconv(.c) LeanObj;",
  "extern fn lean_copy_expand_array_nonlinear(_0: LeanObj, _1: bool) callconv(.c) LeanObj;",
  "extern fn lean_copy_float_array(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_copy_sarray(_0: LeanObj, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_cstr_to_int(_0: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_ctor_scalar_cptr(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_cutsat_propagate_nonlinear(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_data_value_beq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_dbg_sleep(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dbg_stack_trace(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dbg_trace(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dbg_trace_if_shared(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_deactivate_promise(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_deactivate_task(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_dec_ref_cold(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_decode_io_error(_0: c_int, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_decode_lossy_utf8(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_decode_uv_error(_0: c_int, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_demangle_bt_line_cstr(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_demangle_bt_line_cstr_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_display_cumulative_profiling_times() callconv(.c) LeanObj;",
  "extern fn lean_dsimp(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dynlib_get(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dynlib_load(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_dynlib_symbol_run_as_init(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_elab_add_decl(_0: LeanObj, _1: usize, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_elab_add_decl_without_checking(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_emit_llvm(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_ensure_exclusive_array(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_eval_check_meta(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_eval_const(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_eval_const_zig_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_eval_main_decl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) u32;",
  "extern fn lean_eval_main_decl_zig_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) u32;",
  "extern fn lean_event_loop_is_alive() callconv(.c) c_int;",
  "extern fn lean_event_loop_lock() callconv(.c) void;",
  "extern fn lean_event_loop_loop() callconv(.c) LeanObj;",
  "extern fn lean_event_loop_unlock() callconv(.c) void;",
  "extern fn lean_expr_abstract(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_abstract_range(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_data(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_expr_dbg_to_string(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_equal(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_equal_zig_impl(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_eqv(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_eqv_zig_impl(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_has_loose_bvar(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_instantiate(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_instantiate1(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_instantiate_range(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_instantiate_rev(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_instantiate_rev_range(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_lift_loose_bvars(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_lower_loose_bvars(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_lt(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_mk_app(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_app_data(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_expr_mk_bvar(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_const(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_data(_0: u64, _1: LeanObj, _2: u32, _3: u8, _4: u8, _5: u8, _6: u8) callconv(.c) u64;",
  "extern fn lean_expr_mk_forall(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_fvar(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_lambda(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_let(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: u8) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_lit(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_mdata(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_proj(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_mk_sort(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_expr_quick_lt(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_expr_quick_lt_zig_impl(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_extract_mpz_value(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_finalize_formatter() callconv(.c) void;",
  "extern fn lean_finalize_library_core_module() callconv(.c) void;",
  "extern fn lean_finalize_library_module() callconv(.c) void;",
  "extern fn lean_finalize_openssl() callconv(.c) void;",
  "extern fn lean_finalize_stack_overflow() callconv(.c) void;",
  "extern fn lean_finalize_task_manager() callconv(.c) void;",
  "extern fn lean_finalize_thread() callconv(.c) void;",
  "extern fn lean_find_expr(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_find_ext_expr(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_float32_add(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn lean_float32_beq(_0: f32, _1: f32) callconv(.c) u8;",
  "extern fn lean_float32_decLe(_0: f32, _1: f32) callconv(.c) u8;",
  "extern fn lean_float32_decLt(_0: f32, _1: f32) callconv(.c) u8;",
  "extern fn lean_float32_div(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn lean_float32_frexp(_0: f32) callconv(.c) LeanObj;",
  "extern fn lean_float32_isfinite(_0: f32) callconv(.c) u8;",
  "extern fn lean_float32_isinf(_0: f32) callconv(.c) u8;",
  "extern fn lean_float32_isnan(_0: f32) callconv(.c) u8;",
  "extern fn lean_float32_mul(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn lean_float32_negate(_0: f32) callconv(.c) f32;",
  "extern fn lean_float32_of_bits(_0: u32) callconv(.c) f32;",
  "extern fn lean_float32_once_cold(_0: *f32, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) f32) callconv(.c) f32;",
  "extern fn lean_float32_scaleb(_0: f32, _1: LeanObj) callconv(.c) f32;",
  "extern fn lean_float32_sub(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn lean_float32_to_bits(_0: f32) callconv(.c) u32;",
  "extern fn lean_float32_to_float(_0: f32) callconv(.c) f64;",
  "extern fn lean_float32_to_int16(_0: f32) callconv(.c) u16;",
  "extern fn lean_float32_to_int32(_0: f32) callconv(.c) u32;",
  "extern fn lean_float32_to_int64(_0: f32) callconv(.c) u64;",
  "extern fn lean_float32_to_int8(_0: f32) callconv(.c) u8;",
  "extern fn lean_float32_to_isize(_0: f32) callconv(.c) usize;",
  "extern fn lean_float32_to_string(_0: f32) callconv(.c) LeanObj;",
  "extern fn lean_float32_to_uint16(_0: f32) callconv(.c) u16;",
  "extern fn lean_float32_to_uint32(_0: f32) callconv(.c) u32;",
  "extern fn lean_float32_to_uint64(_0: f32) callconv(.c) u64;",
  "extern fn lean_float32_to_uint8(_0: f32) callconv(.c) u8;",
  "extern fn lean_float32_to_usize(_0: f32) callconv(.c) usize;",
  "extern fn lean_float_add(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn lean_float_array_cptr(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_float_array_data(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_float_array_fget(_0: LeanObj, _1: LeanObj) callconv(.c) f64;",
  "extern fn lean_float_array_fset(_0: LeanObj, _1: LeanObj, _2: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_array_get(_0: LeanObj, _1: LeanObj) callconv(.c) f64;",
  "extern fn lean_float_array_get_impl(_0: LeanObj, _1: LeanObj) callconv(.c) f64;",
  "extern fn lean_float_array_mk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_float_array_push(_0: LeanObj, _1: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_array_set(_0: LeanObj, _1: LeanObj, _2: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_array_set_impl(_0: LeanObj, _1: LeanObj, _2: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_array_size(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_float_array_uget(_0: LeanObj, _1: usize) callconv(.c) f64;",
  "extern fn lean_float_array_uget_impl(_0: LeanObj, _1: usize) callconv(.c) f64;",
  "extern fn lean_float_array_uset(_0: LeanObj, _1: usize, _2: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_array_uset_impl(_0: LeanObj, _1: usize, _2: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_beq(_0: f64, _1: f64) callconv(.c) u8;",
  "extern fn lean_float_decLe(_0: f64, _1: f64) callconv(.c) u8;",
  "extern fn lean_float_decLt(_0: f64, _1: f64) callconv(.c) u8;",
  "extern fn lean_float_div(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn lean_float_frexp(_0: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_isfinite(_0: f64) callconv(.c) u8;",
  "extern fn lean_float_isinf(_0: f64) callconv(.c) u8;",
  "extern fn lean_float_isnan(_0: f64) callconv(.c) u8;",
  "extern fn lean_float_mul(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn lean_float_negate(_0: f64) callconv(.c) f64;",
  "extern fn lean_float_of_bits(_0: u64) callconv(.c) f64;",
  "extern fn lean_float_once_cold(_0: *f64, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) f64) callconv(.c) f64;",
  "extern fn lean_float_scaleb(_0: f64, _1: LeanObj) callconv(.c) f64;",
  "extern fn lean_float_sub(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn lean_float_to_bits(_0: f64) callconv(.c) u64;",
  "extern fn lean_float_to_float32(_0: f64) callconv(.c) f32;",
  "extern fn lean_float_to_int16(_0: f64) callconv(.c) u16;",
  "extern fn lean_float_to_int32(_0: f64) callconv(.c) u32;",
  "extern fn lean_float_to_int64(_0: f64) callconv(.c) u64;",
  "extern fn lean_float_to_int8(_0: f64) callconv(.c) u8;",
  "extern fn lean_float_to_isize(_0: f64) callconv(.c) usize;",
  "extern fn lean_float_to_string(_0: f64) callconv(.c) LeanObj;",
  "extern fn lean_float_to_uint16(_0: f64) callconv(.c) u16;",
  "extern fn lean_float_to_uint32(_0: f64) callconv(.c) u32;",
  "extern fn lean_float_to_uint64(_0: f64) callconv(.c) u64;",
  "extern fn lean_float_to_uint8(_0: f64) callconv(.c) u8;",
  "extern fn lean_float_to_usize(_0: f64) callconv(.c) usize;",
  "extern fn lean_free_object(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_free_small(_0: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_free_small_object(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_get_allocated_memory() callconv(.c) usize;",
  "extern fn lean_get_congr_match_equations_for(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_current_time() callconv(.c) LeanObj;",
  "extern fn lean_get_external_class(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_get_external_data(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_get_githash(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_internal_linker_flags(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_ir_extra_const_names(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_get_leanc_extra_flags(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_leanc_internal_flags(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_linker_flags(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_get_match_equations_for(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_max_ctor_fields(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_max_ctor_scalars_size(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_max_ctor_tag(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_max_heartbeat() callconv(.c) usize;",
  "extern fn lean_get_num_attributes() callconv(.c) LeanObj;",
  "extern fn lean_get_set_stderr(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_set_stdin(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_set_stdout(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_slot_idx(_0: c_uint) callconv(.c) c_uint;",
  "extern fn lean_get_stderr() callconv(.c) LeanObj;",
  "extern fn lean_get_stdin() callconv(.c) LeanObj;",
  "extern fn lean_get_stdout() callconv(.c) LeanObj;",
  "extern fn lean_get_structural_rec_arg_pos(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_usize_size(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_get_utf8_first_byte_opt(_0: u8) callconv(.c) c_uint;",
  "extern fn lean_get_utf8_size(_0: u8) callconv(.c) usize;",
  "extern fn lean_get_windows_local_timezone_id_at(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_grind_internalize(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_grind_mk_eq_proof(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_grind_mk_heq_proof(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_grind_preprocess(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_grind_process_new_facts() callconv(.c) LeanObj;",
  "extern fn lean_has_compile_error(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_has_rc(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_hashmap_mk_idx(_0: LeanObj, _1: u64) callconv(.c) usize;",
  "extern fn lean_hashset_mk_idx(_0: LeanObj, _1: u64) callconv(.c) usize;",
  "extern fn lean_inc_heartbeat() callconv(.c) void;",
  "extern fn lean_inc_ret(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_infer_type(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_init_llvm() callconv(.c) LeanObj;",
  "extern fn lean_init_task_manager() callconv(.c) void;",
  "extern fn lean_init_task_manager_using(_0: c_uint) callconv(.c) void;",
  "extern fn lean_initialize() callconv(.c) void;",
  "extern fn lean_initialize_formatter() callconv(.c) void;",
  "extern fn lean_initialize_impl() callconv(.c) void;",
  "extern fn lean_initialize_library_core_module() callconv(.c) void;",
  "extern fn lean_initialize_library_module() callconv(.c) void;",
  "extern fn lean_initialize_openssl() callconv(.c) void;",
  "extern fn lean_initialize_runtime_module() callconv(.c) void;",
  "extern fn lean_initialize_stack_overflow() callconv(.c) void;",
  "extern fn lean_initialize_thread() callconv(.c) void;",
  "extern fn lean_instantiate_expr_mvars(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_instantiate_level_mvars(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int16_abs(_0: u16) callconv(.c) u16;",
  "extern fn lean_int16_add(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_complement(_0: u16) callconv(.c) u16;",
  "extern fn lean_int16_dec_eq(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_int16_dec_le(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_int16_dec_lt(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_int16_div(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_land(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_lor(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_mod(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_mul(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_neg(_0: u16) callconv(.c) u16;",
  "extern fn lean_int16_of_big_int(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_int16_of_int(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_int16_of_nat(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_int16_shift_left(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_shift_right(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_sub(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int16_to_float(_0: u16) callconv(.c) f64;",
  "extern fn lean_int16_to_float32(_0: u16) callconv(.c) f32;",
  "extern fn lean_int16_to_int(_0: u16) callconv(.c) LeanObj;",
  "extern fn lean_int16_to_int32(_0: u16) callconv(.c) u32;",
  "extern fn lean_int16_to_int64(_0: u16) callconv(.c) u64;",
  "extern fn lean_int16_to_int8(_0: u16) callconv(.c) u8;",
  "extern fn lean_int16_to_isize(_0: u16) callconv(.c) usize;",
  "extern fn lean_int16_xor(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_int32_abs(_0: u32) callconv(.c) u32;",
  "extern fn lean_int32_add(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_complement(_0: u32) callconv(.c) u32;",
  "extern fn lean_int32_dec_eq(_0: u32, _1: u32) callconv(.c) u8;",
  "extern fn lean_int32_dec_le(_0: u32, _1: u32) callconv(.c) u8;",
  "extern fn lean_int32_dec_lt(_0: u32, _1: u32) callconv(.c) u8;",
  "extern fn lean_int32_div(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_land(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_lor(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_mod(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_mul(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_neg(_0: u32) callconv(.c) u32;",
  "extern fn lean_int32_of_big_int(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_int32_of_int(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_int32_of_nat(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_int32_shift_left(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_shift_right(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_sub(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int32_to_float(_0: u32) callconv(.c) f64;",
  "extern fn lean_int32_to_float32(_0: u32) callconv(.c) f32;",
  "extern fn lean_int32_to_int(_0: u32) callconv(.c) LeanObj;",
  "extern fn lean_int32_to_int16(_0: u32) callconv(.c) u16;",
  "extern fn lean_int32_to_int64(_0: u32) callconv(.c) u64;",
  "extern fn lean_int32_to_int8(_0: u32) callconv(.c) u8;",
  "extern fn lean_int32_to_isize(_0: u32) callconv(.c) usize;",
  "extern fn lean_int32_xor(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_int64_abs(_0: u64) callconv(.c) u64;",
  "extern fn lean_int64_add(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_complement(_0: u64) callconv(.c) u64;",
  "extern fn lean_int64_dec_eq(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_int64_dec_le(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_int64_dec_lt(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_int64_div(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_land(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_lor(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_mod(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_mul(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_neg(_0: u64) callconv(.c) u64;",
  "extern fn lean_int64_of_big_int(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_int64_of_int(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_int64_of_nat(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_int64_shift_left(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_shift_right(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_sub(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int64_to_float(_0: u64) callconv(.c) f64;",
  "extern fn lean_int64_to_float32(_0: u64) callconv(.c) f32;",
  "extern fn lean_int64_to_int(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_int64_to_int16(_0: u64) callconv(.c) u16;",
  "extern fn lean_int64_to_int32(_0: u64) callconv(.c) u32;",
  "extern fn lean_int64_to_int8(_0: u64) callconv(.c) u8;",
  "extern fn lean_int64_to_int_sint(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_int64_to_isize(_0: u64) callconv(.c) usize;",
  "extern fn lean_int64_xor(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_int8_abs(_0: u8) callconv(.c) u8;",
  "extern fn lean_int8_add(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_complement(_0: u8) callconv(.c) u8;",
  "extern fn lean_int8_dec_eq(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_dec_le(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_dec_lt(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_div(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_land(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_lor(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_mod(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_mul(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_neg(_0: u8) callconv(.c) u8;",
  "extern fn lean_int8_of_big_int(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_int8_of_int(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_int8_of_nat(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_int8_shift_left(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_shift_right(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_sub(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int8_to_float(_0: u8) callconv(.c) f64;",
  "extern fn lean_int8_to_float32(_0: u8) callconv(.c) f32;",
  "extern fn lean_int8_to_int(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_int8_to_int16(_0: u8) callconv(.c) u16;",
  "extern fn lean_int8_to_int32(_0: u8) callconv(.c) u32;",
  "extern fn lean_int8_to_int64(_0: u8) callconv(.c) u64;",
  "extern fn lean_int8_to_isize(_0: u8) callconv(.c) usize;",
  "extern fn lean_int8_xor(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_int_add(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_add(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_div(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_div_exact(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_ediv(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_emod(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_eq(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_big_le(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_big_lt(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_big_mod(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_mul(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_neg(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_big_nonneg(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_big_sub(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_dec_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_int_dec_le(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_int_dec_lt(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_int_dec_nonneg(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_int_div(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_div_exact(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_ediv(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_emod(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_eq(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_le(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_lt(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_mod(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_mul(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_ne(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_int_neg(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_neg_succ_of_nat(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_sub(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_int_to_int(_0: c_int) callconv(.c) LeanObj;",
  "extern fn lean_int_to_nat(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_enable_debug(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_believer_trust_level(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_internal_get_build_type(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_default_max_heartbeat(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_default_max_memory(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_default_options(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_default_options_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_internal_get_default_verbose(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_get_hardware_concurrency(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_internal_has_address_sanitizer(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_has_llvm_backend(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_is_debug(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_is_multi_thread(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_is_stage0(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_internal_panic(_0: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_internal_panic_out_of_memory() callconv(.c) void;",
  "extern fn lean_internal_panic_overflow() callconv(.c) void;",
  "extern fn lean_internal_panic_rc_overflow() callconv(.c) void;",
  "extern fn lean_internal_panic_unreachable() callconv(.c) void;",
  "extern fn lean_internal_set_exit_on_panic(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_internal_set_max_heartbeat(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_internal_set_max_memory(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_internal_set_thread_stack_size(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_io_allocprof(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_app_path() callconv(.c) LeanObj;",
  "extern fn lean_io_as_task(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_as_task_fn(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basemutex_lock(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basemutex_new() callconv(.c) LeanObj;",
  "extern fn lean_io_basemutex_try_lock(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_basemutex_unlock(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_baserecmutex_lock(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_baserecmutex_new() callconv(.c) LeanObj;",
  "extern fn lean_io_baserecmutex_try_lock(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_baserecmutex_unlock(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basesharedmutex_new() callconv(.c) LeanObj;",
  "extern fn lean_io_basesharedmutex_read(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basesharedmutex_try_read(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_basesharedmutex_try_write(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_basesharedmutex_unlock_read(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basesharedmutex_unlock_write(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_basesharedmutex_write(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_bind_task(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_bind_task_fn(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_cancel(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_cancel_core(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_io_check_canceled() callconv(.c) u8;",
  "extern fn lean_io_check_canceled_core() callconv(.c) bool;",
  "extern fn lean_io_condvar_new() callconv(.c) LeanObj;",
  "extern fn lean_io_condvar_notify_all(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_condvar_notify_one(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_condvar_wait(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_create_dir(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_create_tempdir() callconv(.c) LeanObj;",
  "extern fn lean_io_create_tempfile() callconv(.c) LeanObj;",
  "extern fn lean_io_current_dir() callconv(.c) LeanObj;",
  "extern fn lean_io_eprintln(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_eprintln_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_error_to_string(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_error_to_string_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_exit(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_force_exit(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_get_num_heartbeats() callconv(.c) LeanObj;",
  "extern fn lean_io_get_random_bytes(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_io_get_task_state(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_get_task_state_core(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_get_tid() callconv(.c) u64;",
  "extern fn lean_io_getenv(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_hard_link(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_initializing() callconv(.c) u8;",
  "extern fn lean_io_map_task(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_mark_end_initialization() callconv(.c) void;",
  "extern fn lean_io_metadata(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_mono_ms_now() callconv(.c) LeanObj;",
  "extern fn lean_io_mono_nanos_now() callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_flush(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_get_line(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_is_eof(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_prim_handle_is_tty(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_io_prim_handle_lock(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_mk(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_put_str(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_read(_0: LeanObj, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_rewind(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_truncate(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_try_lock(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_unlock(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_prim_handle_write(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_println(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_child_kill(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_child_pid(_0: LeanObj, _1: LeanObj) callconv(.c) u32;",
  "extern fn lean_io_process_child_take_stdin(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_child_try_wait(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_child_wait(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_get_current_dir() callconv(.c) LeanObj;",
  "extern fn lean_io_process_get_pid() callconv(.c) u32;",
  "extern fn lean_io_process_set_current_dir(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_process_spawn(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_promise_new() callconv(.c) LeanObj;",
  "extern fn lean_io_promise_resolve(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_promise_result_opt(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_read_dir(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_realpath(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_remove_dir(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_remove_file(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_rename(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_result_get_error(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_result_is_error(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_io_result_mk_error(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_result_show_error(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_io_result_take_value(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_set_heartbeats(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_symlink_metadata(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_timeit(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_wait(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_wait_any(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_io_wait_any_core(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_ir_export_entries(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_is_array(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_big_object_tag(_0: u8) callconv(.c) bool;",
  "extern fn lean_is_closure(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_exclusive_obj(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_is_expr_def_eq(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_is_external(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_level_def_eq(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_is_mpz(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_mt(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_persistent(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_promise(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_ref(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_reserved_name(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_is_sarray(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_shared(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_string(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_task(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_thunk(_0: LeanObj) callconv(.c) bool;",
  "extern fn lean_is_utf8_next(_0: u8) callconv(.c) bool;",
  "extern fn lean_isize_abs(_0: usize) callconv(.c) usize;",
  "extern fn lean_isize_add(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_complement(_0: usize) callconv(.c) usize;",
  "extern fn lean_isize_dec_eq(_0: usize, _1: usize) callconv(.c) u8;",
  "extern fn lean_isize_dec_le(_0: usize, _1: usize) callconv(.c) u8;",
  "extern fn lean_isize_dec_lt(_0: usize, _1: usize) callconv(.c) u8;",
  "extern fn lean_isize_div(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_land(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_lor(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_mod(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_mul(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_neg(_0: usize) callconv(.c) usize;",
  "extern fn lean_isize_of_big_int(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_isize_of_int(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_isize_of_nat(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_isize_shift_left(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_shift_right(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_sub(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_isize_to_float(_0: usize) callconv(.c) f64;",
  "extern fn lean_isize_to_float32(_0: usize) callconv(.c) f32;",
  "extern fn lean_isize_to_int(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_isize_to_int16(_0: usize) callconv(.c) u16;",
  "extern fn lean_isize_to_int32(_0: usize) callconv(.c) u32;",
  "extern fn lean_isize_to_int64(_0: usize) callconv(.c) u64;",
  "extern fn lean_isize_to_int8(_0: usize) callconv(.c) u8;",
  "extern fn lean_isize_xor(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_kernel_cheap_beta_reduce(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_check(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_check_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_check_with_params_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: u8) callconv(.c) LeanObj;",
  "extern fn lean_kernel_instantiate_type_lparams(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_instantiate_value_lparams(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_is_def_eq(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_is_def_eq_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) u8;",
  "extern fn lean_kernel_is_def_eq_with_params_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: u8) callconv(.c) u8;",
  "extern fn lean_kernel_whnf(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_kernel_whnf_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_level_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_level_eqv(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_level_mk_data(_0: u64, _1: LeanObj, _2: u8, _3: u8) callconv(.c) u64;",
  "extern fn lean_level_mk_imax(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_level_mk_max(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_level_mk_param(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_level_mk_succ(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_level_mk_zero(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_libuv_version(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_list_cons(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_add_attribute_at_index(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_add_case(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_add_function(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_add_global(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_append_basic_block_in_context(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_array_type(_0: LeanObj, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_add(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_alloca(_0: usize, _1: usize, _2: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_br(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_call2(_0: usize, _1: usize, _2: usize, _3: usize, _4: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_build_cond_br(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_gep2(_0: usize, _1: usize, _2: usize, _3: usize, _4: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_build_global_string(_0: usize, _1: usize, _2: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_build_icmp(_0: usize, _1: usize, _2: u64, _3: usize, _4: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_inbounds_gep2(_0: usize, _1: usize, _2: usize, _3: usize, _4: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_build_load2(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_mul(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_not(_0: usize, _1: usize, _2: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_ptr_to_int(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_ret(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_ret_void(_0: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_sext(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_sext_or_trunc(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_store(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_sub(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_build_switch(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u64) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_unreachable(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_build_zext(_0: usize, _1: usize, _2: usize, _3: usize) callconv(.c) usize;",
  "extern fn lean_llvm_clear_insertion_position(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_const_array(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_llvm_const_int(_0: LeanObj, _1: u64, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_const_pointer_null(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_const_string(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_count_basic_blocks(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_llvm_create_builder_in_context(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_create_context() callconv(.c) LeanObj;",
  "extern fn lean_llvm_create_memory_buffer_with_contents_of_file(_0: usize) callconv(.c) usize;",
  "extern fn lean_llvm_create_module(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_create_pass_manager() callconv(.c) LeanObj;",
  "extern fn lean_llvm_create_pass_manager_builder() callconv(.c) LeanObj;",
  "extern fn lean_llvm_create_string_attribute(_0: usize, _1: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_create_target_machine(_0: usize, _1: usize, _2: LeanObj, _3: LeanObj) callconv(.c) usize;",
  "extern fn lean_llvm_dispose_module(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_dispose_pass_manager(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_dispose_pass_manager_builder(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_dispose_target_machine(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_double_type_in_context(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_float_type_in_context(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_function_type(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_basic_block_parent(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_default_target_triple() callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_entry_basic_block(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_first_function(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_first_global(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_first_instruction(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_insert_block(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_named_function(_0: usize, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_named_global(_0: usize, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_next_function(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_next_global(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_target_from_triple(_0: usize) callconv(.c) usize;",
  "extern fn lean_llvm_get_undef(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_get_value_name2(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_initialize_target_info() callconv(.c) LeanObj;",
  "extern fn lean_llvm_int_type_in_context(_0: LeanObj, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_llvm_link_modules(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_module_to_string(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_opaque_pointer_type_in_context(_0: LeanObj, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_llvm_parse_bitcode(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_pass_manager_builder_populate_module_pass_manager(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_pass_manager_builder_set_opt_level(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_pointer_type(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_position_builder_at_end(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_position_builder_before(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_print_module_to_file(_0: usize, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_llvm_print_module_to_string(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_run_pass_manager(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_set_dll_storage_class(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_set_initializer(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_set_linkage(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_set_tail_call(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_llvm_set_visibility(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_target_machine_emit_to_file(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_type_of(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_verify_module(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_void_type_in_context(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_llvm_write_bitcode_to_file(_0: usize, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_main(_0: c_int, _1: [*][*:0]u8) callconv(.c) c_int;",
  "extern fn lean_manual_get_root(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mark_mt(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_mark_persistent(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_max_small_nat(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_antiquot_formatter(_0: LeanObj, _1: LeanObj, _2: u8, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_mk_antiquot_parenthesizer(_0: LeanObj, _1: LeanObj, _2: u8, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_mk_array(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_ascii_string_unchecked(_0: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_mk_cases_on(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_cases_on_zig_impl(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_definition_decl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_definition_val(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj, _5: u8, _6: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_already_exists(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_already_exists_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_already_exists_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_already_exists_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_eof(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_eof_zig_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_hardware_fault(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_hardware_fault_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_illegal_operation(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_illegal_operation_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_inappropriate_type(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_inappropriate_type_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_inappropriate_type_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_inappropriate_type_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_interrupted(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_interrupted_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_invalid_argument(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_invalid_argument_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_invalid_argument_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_invalid_argument_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_file_or_directory(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_file_or_directory_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_such_thing(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_such_thing_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_such_thing_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_no_such_thing_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_other_error(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_other_error_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_permission_denied(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_permission_denied_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_permission_denied_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_permission_denied_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_protocol_error(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_protocol_error_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_busy(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_busy_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_exhausted(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_exhausted_file(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_exhausted_file_zig_impl(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_exhausted_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_vanished(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_resource_vanished_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_time_expired(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_time_expired_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_unsatisfied_constraints(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_unsatisfied_constraints_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_unsupported_operation(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_error_unsupported_operation_zig_impl(_0: u32, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_user_error(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_io_user_error_zig_impl(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_mk_string(_0: [*c]const u8) callconv(.c) LeanObj;",
  "extern fn lean_mk_string_from_bytes(_0: ?*anyopaque, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_mk_string_from_bytes_unchecked(_0: ?*anyopaque, _1: usize) callconv(.c) LeanObj;",
  "extern fn lean_mk_string_unchecked(_0: [*c]const u8, _1: usize, _2: usize) callconv(.c) LeanObj;",
  "extern fn lean_mk_thunk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_name_append_after(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_name_append_before(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_name_append_index_after(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_name_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_name_hash(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_name_hash_ptr(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_name_mk_str(_0: LeanObj, _1: [*:0]const u8) callconv(.c) LeanObj;",
  "extern fn lean_nat_abs(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_big_div_exact(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_big_land(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_big_lor(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_big_shiftr(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_big_xor(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_div_exact(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_gcd(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_land(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_log2(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_lor(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_lxor(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_ne(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_nat_pred(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_shiftl(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_shiftr(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_nat_to_int(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_next_utf8(_0: ?*anyopaque, _1: usize, _2: ?*anyopaque) callconv(.c) c_uint;",
  "extern fn lean_notify_assert(_0: [*:0]const u8, _1: c_int, _2: [*:0]const u8) callconv(.c) void;",
  "extern fn lean_obj_once_cold(_0: *LeanObj, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_object_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_object_data_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_openssl_version(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_option_get_or_block(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_panic(_0: ?*anyopaque, _1: bool) callconv(.c) void;",
  "extern fn lean_panic_fn(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_panic_fn_borrowed(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_pretty_printer_formatter_interpret_parser_descr(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_pretty_printer_parenthesizer_interpret_parser_descr(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_print_expr(_0: LeanObj) callconv(.c) void;",
  "extern fn lean_profileit(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_promise_new() callconv(.c) LeanObj;",
  "extern fn lean_promise_resolve(_0: LeanObj, _1: LeanObj) callconv(.c) void;",
  "extern fn lean_ptr_addr(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_push_unicode_scalar(_0: ?*anyopaque, _1: c_uint) callconv(.c) c_uint;",
  "extern fn lean_register_external_class(_0: ?*anyopaque, _1: ?*anyopaque) callconv(.c) ?*anyopaque;",
  "extern fn lean_replace_expr(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_replace_expr_zig_impl(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_run_init(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_run_init_attrs(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_run_init_zig_impl(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_run_main(_0: MainFn, _1: c_int, _2: [*c][*c]u8) callconv(.c) LeanObj;",
  "extern fn lean_run_mod_init_core(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_runtime_forget(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_runtime_hold(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_runtime_mark_multi_threaded(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_runtime_mark_persistent(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_sarray_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_sarray_capacity(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_sarray_cptr(_0: LeanObj) callconv(.c) [*c]u8;",
  "extern fn lean_sarray_data_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_sarray_dec_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_sarray_elem_size(_0: LeanObj) callconv(.c) c_uint;",
  "extern fn lean_sarray_ensure_capacity(_0: LeanObj, _1: usize, _2: bool) callconv(.c) LeanObj;",
  "extern fn lean_sarray_eq(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_sarray_eq_cold(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_sarray_set_size(_0: LeanObj, _1: usize) callconv(.c) void;",
  "extern fn lean_sarray_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_save_stack_info(_0: bool) callconv(.c) void;",
  "extern fn lean_scalar_to_int(_0: LeanObj) callconv(.c) c_int;",
  "extern fn lean_scalar_to_int64(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_set_exit_on_panic(_0: bool) callconv(.c) void;",
  "extern fn lean_set_external_data(_0: LeanObj, _1: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_set_max_heartbeat(_0: usize) callconv(.c) void;",
  "extern fn lean_set_max_heartbeat_thousands(_0: c_uint) callconv(.c) void;",
  "extern fn lean_set_max_memory(_0: usize) callconv(.c) void;",
  "extern fn lean_set_max_memory_megabyte(_0: c_uint) callconv(.c) void;",
  "extern fn lean_set_non_heap_header(_0: LeanObj, _1: usize, _2: c_uint, _3: c_uint) callconv(.c) void;",
  "extern fn lean_set_non_heap_header_for_big(_0: LeanObj, _1: c_uint, _2: c_uint) callconv(.c) void;",
  "extern fn lean_set_panic_messages(_0: bool) callconv(.c) void;",
  "extern fn lean_set_print_fn(_0: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_setup_args(_0: c_int, _1: [*c][*c]u8) callconv(.c) [*c][*c]u8;",
  "extern fn lean_sharecommon_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_sharecommon_hash(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_sharecommon_quick(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_simp(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_sleep_for(_0: c_uint, _1: c_uint) callconv(.c) void;",
  "extern fn lean_slice_dec_lt(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_slice_hash(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_small_mem_size(_0: ?*anyopaque) callconv(.c) c_uint;",
  "extern fn lean_small_object_size(_0: LeanObj) callconv(.c) c_uint;",
  "extern fn lean_smap_foreach_test(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_sorry(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_st_mk_ref(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_st_ref_get(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_st_ref_ptr_eq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_st_ref_reset(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_st_ref_set(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_st_ref_swap(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_st_ref_take(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_state_sharecommon(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_strict_and(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_strict_or(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_string_any(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_string_append(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_string_capacity(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_string_capitalize(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_compare(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_string_contains(_0: LeanObj, _1: u32) callconv(.c) u8;",
  "extern fn lean_string_cstr(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_string_data(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_data_byte_size(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_string_drop(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_dropright(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_eq(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_string_eq_cold(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_string_foldl(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_from_utf8_unchecked(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_front(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_string_get(_0: LeanObj, _1: usize) callconv(.c) u8;",
  "extern fn lean_string_hash(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_string_intercalate(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_isempty(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_string_isprefixof(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_string_len(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_string_lt(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_string_memcmp(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: LeanObj, _4: LeanObj) callconv(.c) u8;",
  "extern fn lean_string_mk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_ne(_0: LeanObj, _1: LeanObj) callconv(.c) bool;",
  "extern fn lean_string_nextwhile(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_of_usize(_0: usize) callconv(.c) LeanObj;",
  "extern fn lean_string_offsetofpos(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_pos_min(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_pos_sub(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_posof(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_string_push(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_string_pushn(_0: LeanObj, _1: u32, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_to_utf8(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_trim(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_extract(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_get(_0: LeanObj, _1: LeanObj) callconv(.c) u32;",
  "extern fn lean_string_utf8_get_bang(_0: LeanObj, _1: LeanObj) callconv(.c) u32;",
  "extern fn lean_string_utf8_get_fast_cold(_0: [*:0]const u8, _1: usize, _2: usize, _3: u8) callconv(.c) u32;",
  "extern fn lean_string_utf8_get_opt(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_next(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_next_fast_cold(_0: usize, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_prev(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_string_utf8_set(_0: LeanObj, _1: LeanObj, _2: u32) callconv(.c) LeanObj;",
  "extern fn lean_string_validate_utf8(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_substring_all(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_substring_beq(_0: LeanObj, _1: LeanObj) callconv(.c) u8;",
  "extern fn lean_substring_drop(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_substring_extract(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_substring_front(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_substring_get(_0: LeanObj, _1: LeanObj) callconv(.c) u32;",
  "extern fn lean_substring_isempty(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_substring_prev(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_substring_takewhile(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_substring_tostring(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_synth_pending(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_system_platform_emscripten(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_system_platform_nbits(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_system_platform_osx(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_system_platform_target(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_system_platform_windows(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_task_bind(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_task_bind_core(_0: LeanObj, _1: LeanObj, _2: c_uint, _3: bool, _4: bool) callconv(.c) LeanObj;",
  "extern fn lean_task_get(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_task_get_own(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_task_map(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_task_map_core(_0: LeanObj, _1: LeanObj, _2: c_uint, _3: bool, _4: bool) callconv(.c) LeanObj;",
  "extern fn lean_task_pure(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_task_spawn(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_task_spawn_core(_0: LeanObj, _1: c_uint, _2: bool) callconv(.c) LeanObj;",
  "extern fn lean_thunk_get(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_thunk_get_core(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_thunk_get_own(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_thunk_pure(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_to_array(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_closure(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_ctor(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_external(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_promise(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_ref(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_sarray(_0: LeanObj) callconv(.c) ?*anyopaque;",
  "extern fn lean_to_string(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_to_task(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_to_thunk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uint16_add(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_complement(_0: u16) callconv(.c) u16;",
  "extern fn lean_uint16_dec_eq(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_uint16_dec_le(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_uint16_dec_lt(_0: u16, _1: u16) callconv(.c) u8;",
  "extern fn lean_uint16_div(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_land(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_log2(_0: u16) callconv(.c) u16;",
  "extern fn lean_uint16_lor(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_mod(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_mul(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_neg(_0: u16) callconv(.c) u16;",
  "extern fn lean_uint16_of_big_nat(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_uint16_of_nat(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_uint16_of_nat_mk(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_uint16_once_cold(_0: *u16, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) u16) callconv(.c) u16;",
  "extern fn lean_uint16_shift_left(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_shift_right(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_sub(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint16_to_float(_0: u16) callconv(.c) f64;",
  "extern fn lean_uint16_to_float32(_0: u16) callconv(.c) f32;",
  "extern fn lean_uint16_to_nat(_0: u16) callconv(.c) LeanObj;",
  "extern fn lean_uint16_to_uint32(_0: u16) callconv(.c) u32;",
  "extern fn lean_uint16_to_uint64(_0: u16) callconv(.c) u64;",
  "extern fn lean_uint16_to_uint8(_0: u16) callconv(.c) u8;",
  "extern fn lean_uint16_to_usize(_0: u16) callconv(.c) usize;",
  "extern fn lean_uint16_xor(_0: u16, _1: u16) callconv(.c) u16;",
  "extern fn lean_uint32_complement(_0: u32) callconv(.c) u32;",
  "extern fn lean_uint32_div(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_land(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_log2(_0: u32) callconv(.c) u32;",
  "extern fn lean_uint32_mod(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_mul(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_neg(_0: u32) callconv(.c) u32;",
  "extern fn lean_uint32_of_nat_mk(_0: LeanObj) callconv(.c) u32;",
  "extern fn lean_uint32_once_cold(_0: *u32, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) u32) callconv(.c) u32;",
  "extern fn lean_uint32_shift_right(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_sub(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint32_to_float(_0: u32) callconv(.c) f64;",
  "extern fn lean_uint32_to_float32(_0: u32) callconv(.c) f32;",
  "extern fn lean_uint32_to_uint16(_0: u32) callconv(.c) u16;",
  "extern fn lean_uint32_to_uint64(_0: u32) callconv(.c) u64;",
  "extern fn lean_uint32_to_uint8(_0: u32) callconv(.c) u8;",
  "extern fn lean_uint32_to_usize(_0: u32) callconv(.c) usize;",
  "extern fn lean_uint32_xor(_0: u32, _1: u32) callconv(.c) u32;",
  "extern fn lean_uint64_add(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_complement(_0: u64) callconv(.c) u64;",
  "extern fn lean_uint64_dec_eq(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_uint64_dec_le(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_uint64_dec_lt(_0: u64, _1: u64) callconv(.c) u8;",
  "extern fn lean_uint64_div(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_land(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_log2(_0: u64) callconv(.c) u64;",
  "extern fn lean_uint64_lor(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_mix_hash(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_mod(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_mul(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_neg(_0: u64) callconv(.c) u64;",
  "extern fn lean_uint64_of_nat_mk(_0: LeanObj) callconv(.c) u64;",
  "extern fn lean_uint64_once_cold(_0: *u64, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) u64) callconv(.c) u64;",
  "extern fn lean_uint64_shift_left(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_shift_right(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_sub(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint64_to_float(_0: u64) callconv(.c) f64;",
  "extern fn lean_uint64_to_float32(_0: u64) callconv(.c) f32;",
  "extern fn lean_uint64_to_uint16(_0: u64) callconv(.c) u16;",
  "extern fn lean_uint64_to_uint32(_0: u64) callconv(.c) u32;",
  "extern fn lean_uint64_to_uint8(_0: u64) callconv(.c) u8;",
  "extern fn lean_uint64_to_usize(_0: u64) callconv(.c) usize;",
  "extern fn lean_uint64_xor(_0: u64, _1: u64) callconv(.c) u64;",
  "extern fn lean_uint8_add(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_complement(_0: u8) callconv(.c) u8;",
  "extern fn lean_uint8_dec_le(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_dec_lt(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_div(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_log2(_0: u8) callconv(.c) u8;",
  "extern fn lean_uint8_lor(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_mod(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_mul(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_neg(_0: u8) callconv(.c) u8;",
  "extern fn lean_uint8_of_big_nat(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_uint8_of_nat(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_uint8_of_nat_mk(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_uint8_once_cold(_0: *u8, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) u8) callconv(.c) u8;",
  "extern fn lean_uint8_shift_left(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_shift_right(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_sub(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_uint8_to_float(_0: u8) callconv(.c) f64;",
  "extern fn lean_uint8_to_float32(_0: u8) callconv(.c) f32;",
  "extern fn lean_uint8_to_nat(_0: u8) callconv(.c) LeanObj;",
  "extern fn lean_uint8_to_uint16(_0: u8) callconv(.c) u16;",
  "extern fn lean_uint8_to_uint64(_0: u8) callconv(.c) u64;",
  "extern fn lean_uint8_to_usize(_0: u8) callconv(.c) usize;",
  "extern fn lean_uint8_xor(_0: u8, _1: u8) callconv(.c) u8;",
  "extern fn lean_unbox_uint16_zig_impl(_0: LeanObj) callconv(.c) u16;",
  "extern fn lean_unbox_uint8_zig_impl(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_update_env_attributes(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_usize_add_would_overflow(_0: usize, _1: usize) callconv(.c) bool;",
  "extern fn lean_usize_complement(_0: usize) callconv(.c) usize;",
  "extern fn lean_usize_dec_le(_0: usize, _1: usize) callconv(.c) u8;",
  "extern fn lean_usize_dec_lt(_0: usize, _1: usize) callconv(.c) u8;",
  "extern fn lean_usize_div(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_land(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_log2(_0: usize) callconv(.c) usize;",
  "extern fn lean_usize_lor(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_mod(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_mul(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_mul_would_overflow(_0: usize, _1: usize) callconv(.c) bool;",
  "extern fn lean_usize_neg(_0: usize) callconv(.c) usize;",
  "extern fn lean_usize_of_big_nat(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_usize_of_nat_mk(_0: LeanObj) callconv(.c) usize;",
  "extern fn lean_usize_once_cold(_0: *usize, _1: *lean_once_cell_t, _2: *const fn() callconv(.c) usize) callconv(.c) usize;",
  "extern fn lean_usize_shift_left(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_shift_right(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_sub(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_usize_to_float(_0: usize) callconv(.c) f64;",
  "extern fn lean_usize_to_float32(_0: usize) callconv(.c) f32;",
  "extern fn lean_usize_to_uint16(_0: usize) callconv(.c) u16;",
  "extern fn lean_usize_to_uint32(_0: usize) callconv(.c) u32;",
  "extern fn lean_usize_to_uint64(_0: usize) callconv(.c) u64;",
  "extern fn lean_usize_to_uint8(_0: usize) callconv(.c) u8;",
  "extern fn lean_usize_xor(_0: usize, _1: usize) callconv(.c) usize;",
  "extern fn lean_utf8_n_strlen(_0: ?*anyopaque, _1: usize) callconv(.c) usize;",
  "extern fn lean_utf8_strlen(_0: ?*anyopaque) callconv(.c) usize;",
  "extern fn lean_utf8_to_unicode(_0: ?*anyopaque, _1: ?*anyopaque) callconv(.c) c_uint;",
  "extern fn lean_uv_chdir(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_cpu_info() callconv(.c) LeanObj;",
  "extern fn lean_uv_cwd() callconv(.c) LeanObj;",
  "extern fn lean_uv_dns_get_info(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_dns_get_info_helper(_0: LeanObj, _1: LeanObj, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_dns_get_name(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_dns_get_name_helper(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_event_loop_alive() callconv(.c) u8;",
  "extern fn lean_uv_event_loop_configure(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_exepath() callconv(.c) LeanObj;",
  "extern fn lean_uv_get_available_memory() callconv(.c) LeanObj;",
  "extern fn lean_uv_get_constrained_memory() callconv(.c) LeanObj;",
  "extern fn lean_uv_get_free_memory() callconv(.c) LeanObj;",
  "extern fn lean_uv_get_process_title() callconv(.c) LeanObj;",
  "extern fn lean_uv_get_total_memory() callconv(.c) LeanObj;",
  "extern fn lean_uv_getrusage() callconv(.c) LeanObj;",
  "extern fn lean_uv_hrtime() callconv(.c) LeanObj;",
  "extern fn lean_uv_interface_addresses() callconv(.c) LeanObj;",
  "extern fn lean_uv_loop_configure_block_signal_helper(_0: LeanObj) callconv(.c) c_int;",
  "extern fn lean_uv_loop_configure_idle_helper(_0: LeanObj) callconv(.c) c_int;",
  "extern fn lean_uv_ntop_v4(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_ntop_v6(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_environ() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_get_group(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_get_passwd() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_getenv(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_gethostname() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_getpid() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_getppid() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_getpriority(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_homedir() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_setenv(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_setpriority(_0: u64, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_os_tmpdir() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_uname() callconv(.c) LeanObj;",
  "extern fn lean_uv_os_unsetenv(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_pton_v4(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_pton_v6(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_random(_0: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_set_process_title(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_signal_cancel(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_signal_mk(_0: u32, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_signal_next(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_signal_stop(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_accept(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_bind(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_cancel_accept(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_cancel_recv(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_connect(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_getpeername(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_getsockname(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_keepalive(_0: LeanObj, _1: u8, _2: u32) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_listen(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_new() callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_nodelay(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_recv(_0: LeanObj, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_send(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_shutdown(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_try_accept(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_tcp_wait_readable(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_cancel(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_cancel_helper(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_mk(_0: u64, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_mk_helper(_0: u64, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_next(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_next_helper(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_reset(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_reset_helper(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_stop(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_timer_stop_helper(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_bind(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_cancel_recv(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_connect(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_getpeername(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_getsockname(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_new() callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_recv(_0: LeanObj, _1: u64) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_send(_0: LeanObj, _1: LeanObj, _2: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_broadcast(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_membership(_0: LeanObj, _1: LeanObj, _2: LeanObj, _3: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_multicast_interface(_0: LeanObj, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_multicast_loop(_0: LeanObj, _1: u8) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_multicast_ttl(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_set_ttl(_0: LeanObj, _1: u32) callconv(.c) LeanObj;",
  "extern fn lean_uv_udp_wait_readable(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_uv_uptime() callconv(.c) LeanObj;",
  "extern fn lean_validate_utf8(_0: ?*anyopaque, _1: usize, _2: ?*anyopaque, _3: ?*anyopaque) callconv(.c) bool;",
  "extern fn lean_validate_utf8_one(_0: ?*anyopaque, _1: usize, _2: ?*anyopaque) callconv(.c) bool;",
  "extern fn lean_version_get_is_release(_0: LeanObj) callconv(.c) u8;",
  "extern fn lean_version_get_major(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_version_get_minor(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_version_get_patch(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_version_get_special_desc(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_void_mk(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_whnf(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_windows_get_next_transition(_0: LeanObj, _1: u64, _2: u8) callconv(.c) LeanObj;",
  "extern fn lean_zig_current_task_get() callconv(.c) LeanObj;",
  "extern fn lean_zig_current_task_swap(_0: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_zig_in6_addr_to_ipv6_addr(_0: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_zig_in_addr_storage_to_ip_addr(_0: c_short, _1: LeanObj) callconv(.c) LeanObj;",
  "extern fn lean_zig_in_addr_to_ipv4_addr(_0: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_zig_initialize_libuv_signal() callconv(.c) void;",
  "extern fn lean_zig_initialize_libuv_tcp() callconv(.c) void;",
  "extern fn lean_zig_initialize_libuv_timer() callconv(.c) void;",
  "extern fn lean_zig_initialize_libuv_udp() callconv(.c) void;",
  "extern fn lean_zig_ip_addr_ntop(_0: LeanObj, _1: [*]u8, _2: usize) callconv(.c) void;",
  "extern fn lean_zig_ip_addr_to_in_addr_storage(_0: LeanObj, _1: *c_int, _2: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_zig_ipv4_addr_to_in_addr(_0: LeanObj, _1: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_zig_ipv6_addr_to_in6_addr(_0: LeanObj, _1: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_zig_phys_addr_to_mac_addr(_0: [*]u8) callconv(.c) LeanObj;",
  "extern fn lean_zig_promise_resolve_with_code(_0: c_int, _1: LeanObj) callconv(.c) void;",
  "extern fn lean_zig_sockaddr_to_socketaddress(_0: ?*anyopaque) callconv(.c) LeanObj;",
  "extern fn lean_zig_socket_address_to_sockaddr_storage(_0: LeanObj, _1: ?*anyopaque) callconv(.c) void;",
  "extern fn lean_zig_uv_event_loop_init() callconv(.c) void;",
  "extern fn lean_zig_uv_event_loop_run() callconv(.c) void;",
  "extern fn lean_zig_uv_initialize() callconv(.c) void;",
  "extern fn log(_0: f64) callconv(.c) f64;",
  "extern fn log10(_0: f64) callconv(.c) f64;",
  "extern fn log10f(_0: f32) callconv(.c) f32;",
  "extern fn log2(_0: f64) callconv(.c) f64;",
  "extern fn log2f(_0: f32) callconv(.c) f32;",
  "extern fn logf(_0: f32) callconv(.c) f32;",
  "extern fn pow(_0: f64, _1: f64) callconv(.c) f64;",
  "extern fn powf(_0: f32, _1: f32) callconv(.c) f32;",
  "extern fn round(_0: f64) callconv(.c) f64;",
  "extern fn roundf(_0: f32) callconv(.c) f32;",
  "extern fn sin(_0: f64) callconv(.c) f64;",
  "extern fn sinf(_0: f32) callconv(.c) f32;",
  "extern fn sinh(_0: f64) callconv(.c) f64;",
  "extern fn sinhf(_0: f32) callconv(.c) f32;",
  "extern fn sqrt(_0: f64) callconv(.c) f64;",
  "extern fn sqrtf(_0: f32) callconv(.c) f32;",
  "extern fn tan(_0: f64) callconv(.c) f64;",
  "extern fn tanf(_0: f32) callconv(.c) f32;",
  "extern fn tanh(_0: f64) callconv(.c) f64;",
  "extern fn tanhf(_0: f32) callconv(.c) f32;",
]

end RuntimeExterns
