#!/usr/bin/env python3
# Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
# Released under Apache 2.0 license as described in the file LICENSE.
#
"""Generate src/runtime/zig/lean_rt.zig from an EmitZig-generated file's preamble.

The shared module contains the object-layout types, runtime extern declarations,
and inline helpers that are currently duplicated at the top of every file emitted
by EmitZig.  Generated Zig files can import this module instead of repeating the
same ~1700-line preamble.
"""

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the shared EmitZig runtime Zig module."
    )
    parser.add_argument(
        "source",
        nargs="?",
        default=None,
        help="An EmitZig-generated .zig file whose preamble will be used as the module body.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repository root (default: parent of tools/).",
    )
    args = parser.parse_args()

    root: Path = args.root

    if args.source is None:
        # A representative stdlib test that exercises a broad set of runtime externs.
        source = root / "build" / "release" / "stage1" / "tests" / "emitzig-stdlib" / "StdlibBitVec.zig"
    else:
        source = Path(args.source)

    if not source.is_file():
        print(f"source file not found: {source}", file=sys.stderr)
        print(
            "Build with LEAN_ZIG_RUNTIME=ON and run an emitzig/stdlib test first.",
            file=sys.stderr,
        )
        return 1

    lines = source.read_text().splitlines()
    fwd_idx = next(
        (i for i, line in enumerate(lines) if line.strip() == "// forward declarations"),
        len(lines),
    )
    preamble = lines[:fwd_idx]

    out_lines = [
        "// Copyright (c) 2026 Lean FRO, LLC. All rights reserved.",
        "// Released under Apache 2.0 license as described in the file LICENSE.",
        "/// Auto-generated from the EmitZig preamble.",
        "/// Do not edit by hand; regenerate via tools/gen-lean-rt-zig.py.",
        "",
    ]

    for line in preamble:
        stripped = line.rstrip()
        if stripped.startswith("// generated by emitzig") or stripped.startswith("// module:"):
            continue
        if stripped.startswith(("const ", "extern fn ", "inline fn ", "fn ")):
            out_lines.append("pub " + stripped)
        else:
            out_lines.append(stripped)

    output = root / "src" / "runtime" / "zig" / "lean_rt.zig"
    output.write_text("\n".join(out_lines) + "\n")
    print(f"wrote {output} ({len(out_lines)} lines)")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
